name: Deployment Workflow
on:
  push:
    branches:
      - main

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: for film_cabinet ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          sudo cp -r /var/www/Film-Cabinet-Flask /home/film-cabinet/Documents/websiteFilesBackUp/
          cd /var/www/Film-Cabinet-Flask/
          sudo git pull