name: Deployment Workflow
on:
  push:
    branches:
      - main

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: for film_cabinet ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/Film-Cabinet-Flask/
          git add * 
          git stash
          git pull https://github.com/jgutierrezCSU/Film-Cabinet-Flask.git 
          git status
      